<Solution xmlns:i="http://www.w3.org/2001/XMLSchema-instance" z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns="http://schemas.datacontract.org/2004/07/NationalInstruments.PackageBuilder.Engine">
    <Name>Builder</Name>
    <SourceItems>
        <SourceItem z:Id="i2">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i3">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i4">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i5">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i6">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Automotive Ethernet Bus Monitor UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i7">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i8">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i9">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i10">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i11">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i12">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i13">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i14">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i15">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\BuiltUI\CAN-LIN Raw Bus Capture UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i16">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i17">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i18">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i19">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i20">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i21">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i22">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i23">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i24">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i7" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i25">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i8" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i26">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i9" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i27">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i10" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i28">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i11" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i29">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i12" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i30">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i13" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i31">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i14" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i32">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i15" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i33">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i20" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i34">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i21" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i35">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i22" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i36">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i23" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i37">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i24" />
                <SourceItem z:Ref="i25" />
                <SourceItem z:Ref="i26" />
                <SourceItem z:Ref="i27" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i38">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i28" />
                <SourceItem z:Ref="i29" />
                <SourceItem z:Ref="i30" />
                <SourceItem z:Ref="i31" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i39">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i33" />
                <SourceItem z:Ref="i34" />
                <SourceItem z:Ref="i35" />
                <SourceItem z:Ref="i36" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i40">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i6" />
                <SourceItem z:Ref="i37" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i41">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture\CAN-LIN Raw Bus Capture</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i16" />
                <SourceItem z:Ref="i17" />
                <SourceItem z:Ref="i18" />
                <SourceItem z:Ref="i19" />
                <SourceItem z:Ref="i32" />
                <SourceItem z:Ref="i39" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i42">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\CAN-LIN Raw Bus Capture</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i41" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i43">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor\Automotive Ethernet Bus Monitor</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i2" />
                <SourceItem z:Ref="i3" />
                <SourceItem z:Ref="i4" />
                <SourceItem z:Ref="i5" />
                <SourceItem z:Ref="i40" />
                <SourceItem z:Ref="i38" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i44">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds\Auto-Eth Bus Monitor</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i43" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i45">
            <PluginConfigurationOptions />
            <RelativePath>..\..\labview\builds</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i44" />
                <SourceItem z:Ref="i42" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
    </SourceItems>
    <InputSourceItems>
        <SourceItem z:Ref="i45" />
    </InputSourceItems>
    <Distributions>
        <Distribution z:Id="i46" i:type="Package">
            <DistributionItems>
                <DistributionItem z:Id="i47" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments</DestinationRelativePath>
                    <Name>National Instruments</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i48" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins</DestinationRelativePath>
                    <Name>Plug-Ins</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i49" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements</DestinationRelativePath>
                    <Name>Measurements</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i50" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor</DestinationRelativePath>
                    <Name>Automotive Ethernet Bus Monitor</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i51" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.aliases</DestinationRelativePath>
                    <Name>AutomotiveEthernetBusMonitor.aliases</Name>
                    <SourceItem z:Ref="i2" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i52" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.exe</DestinationRelativePath>
                    <Name>AutomotiveEthernetBusMonitor.exe</Name>
                    <SourceItem z:Ref="i3" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i53" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.ini</DestinationRelativePath>
                    <Name>AutomotiveEthernetBusMonitor.ini</Name>
                    <SourceItem z:Ref="i4" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i54" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\AutomotiveEthernetBusMonitor.serviceconfig</DestinationRelativePath>
                    <Name>AutomotiveEthernetBusMonitor.serviceconfig</Name>
                    <SourceItem z:Ref="i5" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i55" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i56" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Automotive Ethernet Bus Monitor UI.lvlibp</DestinationRelativePath>
                    <Name>Automotive Ethernet Bus Monitor UI.lvlibp</Name>
                    <SourceItem z:Ref="i6" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i57" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i58" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i59" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i7" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i60" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i61" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i8" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i62" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i63" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i9" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i64" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i65" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\BuiltUI\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i10" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i66" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i67" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i68" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i11" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i69" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i70" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i12" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i71" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i72" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i13" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i73" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i74" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\Automotive Ethernet Bus Monitor\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i14" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i75" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture</DestinationRelativePath>
                    <Name>CAN-LIN Raw Bus Capture</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i76" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.aliases</DestinationRelativePath>
                    <Name>CAN-LINRawBusCapture.aliases</Name>
                    <SourceItem z:Ref="i16" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i77" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.exe</DestinationRelativePath>
                    <Name>CAN-LINRawBusCapture.exe</Name>
                    <SourceItem z:Ref="i17" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i78" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.ini</DestinationRelativePath>
                    <Name>CAN-LINRawBusCapture.ini</Name>
                    <SourceItem z:Ref="i18" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i79" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\CAN-LINRawBusCapture.serviceconfig</DestinationRelativePath>
                    <Name>CAN-LINRawBusCapture.serviceconfig</Name>
                    <SourceItem z:Ref="i19" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i80" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i81" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\BuiltUI\CAN-LIN Raw Bus Capture UI.lvlibp</DestinationRelativePath>
                    <Name>CAN-LIN Raw Bus Capture UI.lvlibp</Name>
                    <SourceItem z:Ref="i15" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i82" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i83" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i84" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i20" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i85" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i86" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i21" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i87" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i88" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i22" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i89" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i90" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\Plug-Ins\Measurements\CAN-LIN Raw Bus Capture\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i23" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
            </DistributionItems>
            <Name>Hardware Validation Plugins</Name>
            <OutputDirectory>..\..\..\..</OutputDirectory>
            <PluginConfigurationOptions />
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <Architecture>windows_x64</Architecture>
            <BuildStatus z:Id="i91">
                <BuildEverSuccessful>true</BuildEverSuccessful>
                <FileName>plugins_1.0.0.1_windows_x64.nipkg</FileName>
                <Version>1.0.0.1</Version>
            </BuildStatus>
            <CompanyName>MyCompany</CompanyName>
            <CustomExecutes />
            <DisplayName>Hardware Validation Plugins</DisplayName>
            <FileName>plugins_1.0.0.1_windows_x64.nipkg</FileName>
            <MaintainerEmail>jesse.rosart-brodnitz@emerson.com</MaintainerEmail>
            <MaintainerName>National Instruments ADAS</MaintainerName>
            <Messages xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <PackageName>plugins</PackageName>
            <PackageRelationships />
            <ProductName>MyProduct</ProductName>
            <Section>Application Software</Section>
            <Synopsis>Hardware Validation Plugins</Synopsis>
            <Version>1.0.0.1</Version>
        </Distribution>
    </Distributions>
    <Feeds />
    <DistributionGroups>
        <DistributionGroup z:Id="i92">
            <Distributions>
                <Distribution z:Ref="i46" />
            </Distributions>
            <Name>Distribution Group</Name>
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <StageDirectory>ProcessingStage</StageDirectory>
        </DistributionGroup>
    </DistributionGroups>
    <TestStandMode>true</TestStandMode>
    <PluginConfigurationOptions>
        <ConfigurationOption z:Id="i93">
            <Definition z:Id="i94">
                <Description i:nil="true" />
                <Name>TestStand Options</Name>
            </Definition>
            <HasDefaultValues>true</HasDefaultValues>
            <Value z:Id="i95" i:type="DialogConfigurationOptionValue">
                <Values>
                    <ConfigurationOptionValue z:Id="i96" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i97" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i98" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i99" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i100" i:type="StringConfigurationOptionValue">
                        <Value>SupportVIs</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i101" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i102" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i103" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i104" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i105" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i106" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i107" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i108" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i109" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i110" i:type="PathConfigurationOptionValue">
                        <RelativePath />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i111" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i112" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i113" i:type="StringConfigurationOptionValue">
                        <Value>[BootVolume]</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i114" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i115" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i116" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i117" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i118" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i119" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i120" i:type="BooleanConfigurationOptionValue" />
                </Values>
            </Value>
        </ConfigurationOption>
    </PluginConfigurationOptions>
</Solution>